=== bozobjekovic/Xml_web_services/XMLProject2016/data/akt_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.tim9.com/akt" xmlns:akt="http://www.tim9.com/akt">
    <xs:element name="Akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="akt:Preambula"/>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Deo"/>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Clan"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id"/>
            <xs:attribute name="naslov" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Deo">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Glava"/>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Clan"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id"/>
            <xs:attribute name="redniBroj" type="xs:string"/>
            <xs:attribute name="naslov" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glava">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Odeljak"/>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Clan"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id"/>
            <xs:attribute name="naslov" type="xs:string"/>
            <xs:attribute name="redniBroj" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" minOccurs="1" ref="akt:Pododeljak"/>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Clan"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id"/>
            <xs:attribute name="naslov" type="xs:string"/>
            <xs:attribute name="redniBroj" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Pododeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="akt:Clan"/>
            </xs:sequence>
            <xs:attribute name="id"/>
            <xs:attribute name="naslov" type="xs:string"/>
            <xs:attribute name="redniBroj" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Clan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="akt:Stav"/>
            </xs:sequence>
            <xs:attribute name="id"/>
            <xs:attribute name="naslov" type="xs:string"/>
            <xs:attribute name="redniBroj" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stav">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Tacka"/>
                    <xs:element name="Sadrzaj" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Tacka">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Podtacka"/>
                    <xs:element name="Sadrzaj" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id"/>
            <xs:attribute name="redniBroj" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podtacka">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Alineja"/>
                    <xs:element name="Sadrzaj" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id"/>
            <xs:attribute name="redniBroj" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Preambula">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PravniOsnov" type="xs:string"/>
                <xs:element name="NazivOrgana" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Alineja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bozobjekovic/Xml_web_services/XMLProject2016/data/akt.xml
<?xml version="1.0" encoding="UTF-8"?>
<akt:Akt xmlns:akt="http://www.tim9.com/akt"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.tim9.com/akt file:/D:/7.%20SEMESTAR/XML/XML/Xml_web_services/XMLProject2016/data/akt_schema.xsd" id="QsX4" naslov="Flvkk74O7juF37KVn6soZjD5NZmpFF">
    <akt:Preambula>
        <akt:PravniOsnov>oRgGtL1R_Qxa</akt:PravniOsnov>
        <akt:NazivOrgana>pPXcm.I6Gck4vzLfoyseVIRY96FT_5</akt:NazivOrgana>
    </akt:Preambula>
    <akt:Clan id="h6y576y-_CM" naslov="wl" redniBroj="w-4TbCzt3Fz23eMYw">
        <akt:Stav id="RxKAWoVxiIwUZ-XtNVweQT">
            <akt:Sadrzaj>ZlQkRZPsdNw2oFfaWK40</akt:Sadrzaj>
        </akt:Stav>
        <akt:Stav id="vo.fijrqfz9.5TAG-nSVXHD1f">
            <akt:Tacka id="uG4aSVleiTqi-nJtMoz6s9tBn" redniBroj="utlIF0n5">
                <akt:Sadrzaj>antTh5ECm-eR</akt:Sadrzaj>
            </akt:Tacka>
            <akt:Tacka id="CgA_naTxbPXRQPcu8oS" redniBroj="JDUCRuE-N">
                <akt:Podtacka id="Pzr0" redniBroj="HYf7.tj4E.2Rlx_9LrEIy63E">
                    <akt:Sadrzaj>ebTuM52U-FG</akt:Sadrzaj>
                </akt:Podtacka>
                <akt:Podtacka id="Y3kz_dPJPKr0VSBR.WBTR1dC9cjPCt" redniBroj="A">
                    <akt:Sadrzaj>NcGU0z5WL0AjuJqSxs1</akt:Sadrzaj>
                </akt:Podtacka>
            </akt:Tacka>
        </akt:Stav>
    </akt:Clan>
    <akt:Clan id="_kjEajjMcbXkcYY" naslov="SGwAgSOjIbvw" redniBroj="URjpRrUjbelv2cqbdDowiqWv9aM">
        <akt:Stav id="AT4Oac6WnBHSOBIiZVkLKZw2aHiOh">
            <akt:Tacka id="OaiFkoEqPwlkmUyqoknIKw5q" redniBroj="QfO2.bg">
                <akt:Sadrzaj>G_yycFt.vicP</akt:Sadrzaj>
            </akt:Tacka>
            <akt:Tacka id="xA9Jjqqnog-Kx6RkIAkW6Q" redniBroj="ZDAmg7wHq257YgggI9067wXv-zu">
                <akt:Podtacka id="csaxcZdaDsh022hRFF4v4-Wk" redniBroj="JZqpgCm">
                    <akt:Sadrzaj>inT9NgxENtPc</akt:Sadrzaj>
                </akt:Podtacka>
                <akt:Podtacka id="u64R_q1cgf6md" redniBroj="D5Brcn.OrTqjl6o3G4qhowe_iBknT">
                    <akt:Sadrzaj>gxPx7A-H</akt:Sadrzaj>
                </akt:Podtacka>
            </akt:Tacka>
        </akt:Stav>
        <akt:Stav id="tK7b_w">
            <akt:Tacka id="T_blNo_E4xj2ZtgJcogU" redniBroj="cv4Rf2_G1mMy">
                <akt:Podtacka id="MRsDdiETB2ZH8Dialle0" redniBroj="Ou81QStw">
                    <akt:Alineja id="m.eYytaS">
                        <akt:Sadrzaj>F0NaMpJ.OHvmpY</akt:Sadrzaj>
                    </akt:Alineja>
                    <akt:Alineja id="NX_SGS7N8tvQ">
                        <akt:Sadrzaj>HQAxAWt-6OQ66Con.8k-m</akt:Sadrzaj>
                    </akt:Alineja>
                </akt:Podtacka>
                <akt:Podtacka id="TRNlu" redniBroj="Vb0oapS">
                    <akt:Sadrzaj>gB4v_1bhffspXzUXSWWq</akt:Sadrzaj>
                </akt:Podtacka>
            </akt:Tacka>
            <akt:Tacka id="LE3FH" redniBroj="j">
                <akt:Sadrzaj>zjtTwup</akt:Sadrzaj>
            </akt:Tacka>
        </akt:Stav>
    </akt:Clan>
</akt:Akt>

=== bozobjekovic/Xml_web_services/XMLProject2016/data/akt1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Akt xmlns="http://www.tim9.com/akt"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.tim9.com/akt file:/E:/7.%20semestar/XML%20i%20veb%20servisi/Projekat/Projekat/Xml_web_services/XMLProject2016/data/akt_schema.xsd" id="id1" naslov="naslov1">
    <Preambula>
        <PravniOsnov>PravniOsnov0</PravniOsnov>
        <NazivOrgana>NazivOrgana0</NazivOrgana>
        <Oblast property="oblast" datatype="xs:string">Oblast0</Oblast>
        <Status property="status" datatype="xs:string">Status0</Status>
        <DatumPredaje property="datumPredaje" datatype="xs:date">2006-05-04</DatumPredaje>
        <DatumObjave property="datumObjave" datatype="xs:date">DatumObjave0</DatumObjave>
        <BrojGlasovaZa property="za" datatype="xs:date">0</BrojGlasovaZa>
        <BrojGlasovaProtiv property="protiv" datatype="xs:date">0</BrojGlasovaProtiv>
        <BrojGlasovaUzdrzano property="uzdrzano" datatype="xs:date">0</BrojGlasovaUzdrzano>
    </Preambula>
    <Deo id="id3" redniBroj="redniBroj1" naslov="naslov3">
        <Clan id="id5" naslov="naslov5" redniBroj="redniBroj3">
            <Stav id="id7">
                <Tacka id="id9" redniBroj="redniBroj5">
                    <Podtacka id="id11" redniBroj="redniBroj7">
                        <Sadrzaj>Sadrzaj0</Sadrzaj>
                    </Podtacka>
                    <Podtacka id="id13" redniBroj="redniBroj9">
                        <Sadrzaj>Sadrzaj1</Sadrzaj>
                    </Podtacka>
                </Tacka>
                <Tacka id="id15" redniBroj="redniBroj11">
                    <Podtacka id="id17" redniBroj="redniBroj13">
                        <Sadrzaj>Sadrzaj2</Sadrzaj>
                    </Podtacka>
                    <Podtacka id="id19" redniBroj="redniBroj15">
                        <Sadrzaj>Sadrzaj3</Sadrzaj>
                    </Podtacka>
                </Tacka>
            </Stav>
            <Stav id="id21">
                <Tacka id="id23" redniBroj="redniBroj17">
                    <Sadrzaj>Sadrzaj4</Sadrzaj>
                </Tacka>
                <Tacka id="id25" redniBroj="redniBroj19">
                    <Sadrzaj>Sadrzaj5</Sadrzaj>
                </Tacka>
            </Stav>
        </Clan>
        <Clan id="id27" naslov="naslov7" redniBroj="redniBroj21">
            <Stav id="id29">
                <Tacka id="id31" redniBroj="redniBroj23">
                    <Podtacka id="id33" redniBroj="redniBroj25">
                        <Alineja id="id35">
                            <Sadrzaj>Sadrzaj6</Sadrzaj>
                        </Alineja>
                        <Alineja id="id37">
                            <Sadrzaj>Sadrzaj7</Sadrzaj>
                        </Alineja>
                    </Podtacka>
                    <Podtacka id="id39" redniBroj="redniBroj27">
                        <Alineja id="id41">
                            <Sadrzaj>Sadrzaj8</Sadrzaj>
                        </Alineja>
                        <Alineja id="id43">
                            <Sadrzaj>Sadrzaj9</Sadrzaj>
                        </Alineja>
                    </Podtacka>
                </Tacka>
                <Tacka id="id45" redniBroj="redniBroj29">
                    <Sadrzaj>Sadrzaj10</Sadrzaj>
                </Tacka>
            </Stav>
            <Stav id="id47">
                <Sadrzaj>Sadrzaj11</Sadrzaj>
            </Stav>
        </Clan>
    </Deo>
    <Deo id="id49" redniBroj="redniBroj31" naslov="naslov9">
        <Clan id="id51" naslov="naslov11" redniBroj="redniBroj33">
            <Stav id="id53">
                <Tacka id="id55" redniBroj="redniBroj35">
                    <Podtacka id="id57" redniBroj="redniBroj37">
                        <Sadrzaj>Sadrzaj12</Sadrzaj>
                    </Podtacka>
                    <Podtacka id="id59" redniBroj="redniBroj39">
                        <Alineja id="id61">
                            <Sadrzaj>Sadrzaj13</Sadrzaj>
                        </Alineja>
                        <Alineja id="id63">
                            <Sadrzaj>Sadrzaj14</Sadrzaj>
                        </Alineja>
                    </Podtacka>
                </Tacka>
                <Tacka id="id65" redniBroj="redniBroj41">
                    <Podtacka id="id67" redniBroj="redniBroj43">
                        <Alineja id="id69">
                            <Sadrzaj>Sadrzaj15</Sadrzaj>
                        </Alineja>
                        <Alineja id="id71">
                            <Sadrzaj>Sadrzaj16</Sadrzaj>
                        </Alineja>
                    </Podtacka>
                    <Podtacka id="id73" redniBroj="redniBroj45">
                        <Alineja id="id75">
                            <Sadrzaj>Sadrzaj17</Sadrzaj>
                        </Alineja>
                        <Alineja id="id77">
                            <Sadrzaj>Sadrzaj18</Sadrzaj>
                        </Alineja>
                    </Podtacka>
                </Tacka>
            </Stav>
            <Stav id="id79">
                <Sadrzaj>Sadrzaj19</Sadrzaj>
            </Stav>
        </Clan>
        <Clan id="id81" naslov="naslov13" redniBroj="redniBroj47">
            <Stav id="id83">
                <Tacka id="id85" redniBroj="redniBroj49">
                    <Sadrzaj>Sadrzaj20</Sadrzaj>
                </Tacka>
                <Tacka id="id87" redniBroj="redniBroj51">
                    <Podtacka id="id89" redniBroj="redniBroj53">
                        <Alineja id="id91">
                            <Sadrzaj>Sadrzaj21</Sadrzaj>
                        </Alineja>
                        <Alineja id="id93">
                            <Sadrzaj>Sadrzaj22</Sadrzaj>
                        </Alineja>
                    </Podtacka>
                    <Podtacka id="id95" redniBroj="redniBroj55">
                        <Sadrzaj>Sadrzaj23</Sadrzaj>
                    </Podtacka>
                </Tacka>
            </Stav>
            <Stav id="id97">
                <Sadrzaj>Sadrzaj24</Sadrzaj>
            </Stav>
        </Clan>
    </Deo>
</Akt>
